# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zeitgeist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WaterfallGrid', '~> 0.4.0'

  # Pods for zeitgeist

  target 'zeitgeistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zeitgeistUITests' do
    # Pods for testing
  end

end
